language: python
python:
  - "3.5"

services:
  - mysql

# command to install dependencies
install:
  - "pip3 install -r requirements.txt"

before_script:
  - mysql -e 'create database sldb;'

# command to run the tests
script: python manage.py test
