-- MySQL Script generated by MySQL Workbench
-- 12/02/16 12:01:13
-- Model: New Model    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TimeTracker` DEFAULT CHARACTER SET utf8 ;
USE `TimeTracker` ;

-- -----------------------------------------------------
-- Table `TimeTracker`.`College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`College` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`College` (
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Department` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Department` (
  `name` VARCHAR(45) NOT NULL,
  `college_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `college_fk`
    FOREIGN KEY (`name`)
    REFERENCES `TimeTracker`.`College` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Course` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Course` (
  `id` VARCHAR(8) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_fk_idx` (`name` ASC),
  CONSTRAINT `department_fk`
    FOREIGN KEY (`name`)
    REFERENCES `TimeTracker`.`Department` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL,
  `is_superuser` TINYINT(1) NOT NULL DEFAULT 0,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Community_Partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Community_Partner` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Community_Partner` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Project` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `course` VARCHAR(8) NULL,
  `community_partner_id` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `description` MEDIUMTEXT NULL,
  `longitude` DECIMAL(9,6) NULL,
  `latitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`),
  INDEX `pj_course_number_id_fk_idx` (`course` ASC),
  INDEX `community_id_fk_idx` (`community_partner_id` ASC),
  CONSTRAINT `pj_course_number_id_fk`
    FOREIGN KEY (`course`)
    REFERENCES `TimeTracker`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `community_id_fk`
    FOREIGN KEY (`community_partner_id`)
    REFERENCES `TimeTracker`.`Community_Partner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Semester` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Semester` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Enrollment` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `course` VARCHAR(8) NOT NULL,
  `project_id` INT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `crn` VARCHAR(5) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id_f_idx` (`course` ASC),
  INDEX `semester_name_fk_idx` (`semester` ASC),
  INDEX `en_project_id_fk_idx` (`project_id` ASC),
  CONSTRAINT `student_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `TimeTracker`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_id_fk`
    FOREIGN KEY (`course`)
    REFERENCES `TimeTracker`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `semester_name_fk`
    FOREIGN KEY (`semester`)
    REFERENCES `TimeTracker`.`Semester` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `en_project_id_fk`
    FOREIGN KEY (`project_id`)
    REFERENCES `TimeTracker`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Record_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Record_Category` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Record_Category` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Record` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enrollment_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `start_time` TIMESTAMP(6) NULL,
  `total_hours` DECIMAL(4,2) NOT NULL,
  `longitude` DECIMAL(9,6) NOT NULL,
  `latitude` DECIMAL(9,6) NULL,
  `category_id` VARCHAR(45) NOT NULL,
  `is_active` TINYINT(1) NULL,
  `comments` MEDIUMTEXT NULL,
  `extra_field` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `project_id_idx` (`project_id` ASC),
  INDEX `enrollment_id_fk_idx` (`enrollment_id` ASC),
  INDEX `category_id_fk_idx` (`category_id` ASC),
  CONSTRAINT `project_id_fk`
    FOREIGN KEY (`project_id`)
    REFERENCES `TimeTracker`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `enrollment_id_fk`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `TimeTracker`.`Enrollment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `TimeTracker`.`Record_Category` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `auth_user` AUTO_INCREMENT = 1;
ALTER TABLE `auth_user` MODIFY COLUMN is_superuser BOOL NOT NULL DEFAULT 0;
ALTER TABLE `auth_user` MODIFY COLUMN is_staff BOOL NOT NULL DEFAULT 0;
ALTER TABLE `auth_user` MODIFY COLUMN is_active BOOL NOT NULL DEFAULT 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;