-- MySQL Script generated by MySQL Workbench
-- 11/20/16 15:29:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TimeTracker` DEFAULT CHARACTER SET utf8 ;
USE `TimeTracker` ;

-- -----------------------------------------------------
-- Table `TimeTracker`.`College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`College` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`College` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Department` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `college_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `college_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `TimeTracker`.`College` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Course` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Course` (
  `course_number` VARCHAR(8) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `semester_id` VARCHAR(8) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`course_number`, `semester_id`),
  INDEX `department_id_idx` (`department_id` ASC),
  CONSTRAINT `department_id_fk`
    FOREIGN KEY (`department_id`)
    REFERENCES `TimeTracker`.`Department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`User` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `groups` VARCHAR(45) NULL,
  `is_active` TINYINT(1) NULL,
  `last_login` DATETIME NULL,
  `date_joined` DATETIME NULL,
  PRIMARY KEY (`id`, `username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Community_Partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Community_Partner` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Community_Partner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Project` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `community_partner_id` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `description` MEDIUMTEXT NULL,
  `location` POINT NULL,
  PRIMARY KEY (`id`),
  INDEX `community_partner_id_idx` (`community_partner_id` ASC),
  CONSTRAINT `community_partner_id_fk`
    FOREIGN KEY (`community_partner_id`)
    REFERENCES `TimeTracker`.`Community_Partner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Record_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Record_Category` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Record_Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Record` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `course_number` VARCHAR(8) NOT NULL,
  `project_id` INT NOT NULL,
  `date` DATE NULL,
  `start_time` TIMESTAMP(6) NULL,
  `total_hours` DECIMAL(4,2) NOT NULL,
  `location` POINT NULL,
  `category_id` INT NOT NULL,
  `comments` MEDIUMTEXT NULL,
  `extra_field` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `project_id_idx` (`project_id` ASC),
  INDEX `category_id_idx` (`category_id` ASC),
  INDEX `course_number_idx` (`course_number` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `TimeTracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_id_fk`
    FOREIGN KEY (`project_id`)
    REFERENCES `TimeTracker`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `TimeTracker`.`Record_Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_number_fk`
    FOREIGN KEY (`course_number`)
    REFERENCES `TimeTracker`.`Course` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TimeTracker`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `TimeTracker`.`Enrollment` (
  `user_id` INT NOT NULL,
  `course_number` VARCHAR(8) NOT NULL,
  `current_class` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`, `course_number`),
  INDEX `course_number_idx` (`course_number` ASC),
  CONSTRAINT `user_id_enroll_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `TimeTracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_number_enroll_fk`
    FOREIGN KEY (`course_number`)
    REFERENCES `TimeTracker`.`Course` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


alter table `College` auto_increment = 1001;
alter table `Community_Partner` auto_increment = 1001;
alter table `Department` auto_increment = 1001;
alter table `Project` auto_increment = 1001;
alter table `Record` auto_increment = 1;
alter table `Record_Category` auto_increment = 1;
alter table `User` auto_increment = 101;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
