# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Community_Partner',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=45)),
                ('semester_id', models.CharField(max_length=8)),
            ],
            options={
                'managed': False,
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('extra_field', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='RecordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Record_Category',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.College')),
                ('name', models.CharField(max_length=45)),
                ('college_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Department',
            },
        ),
    ]
