# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161116_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
        migrations.AlterModelOptions(
            name='communitypartner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectlocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recordcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
