# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161130_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('A', 'Admin')], default='S', max_length=1),
        ),
    ]
