# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161130_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcategory',
            name='name',
            field=models.CharField(choices=[('TO', 'Trainings & Orientations'), ('DS', 'Direct Service'), ('IR', 'Individual Research & Planning'), ('TR', 'Team Research & Planning')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
