# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161201_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
