# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20161201_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Project'),
        ),
    ]
