# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161203_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
