# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 01:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20161203_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='required_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='comments',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
